# Generated by Django 3.0.6 on 2020-05-24 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoadingFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('directions', models.TextField(max_length=2000, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('directions', models.TextField(max_length=2000, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('crew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frac.Crew')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frac.Operator')),
                ('sand_type', models.ManyToManyField(to='frac.SandType')),
                ('serviceco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frac.ServiceCo')),
            ],
        ),
        migrations.CreateModel(
            name='Prefill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prefil', models.DateField()),
                ('po', models.CharField(max_length=30, null=True)),
                ('total_sand', models.CharField(max_length=30, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('loading_facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frac.LoadingFacility')),
                ('sandtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frac.SandType')),
                ('well', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frac.Well')),
            ],
        ),
    ]
