# Generated by Django 3.0.6 on 2020-05-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='sand_type',
            field=models.ManyToManyField(blank=True, to='frac.SandType'),
        ),
    ]
