# Generated by Django 3.0.6 on 2020-05-24 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0002_auto_20200524_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='sand_type',
        ),
    ]
