# Generated by Django 3.0.6 on 2020-05-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0003_remove_well_sand_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='sand_type',
            field=models.ManyToManyField(blank=True, to='frac.SandType'),
        ),
    ]
