# Generated by Django 3.0.6 on 2020-05-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0004_well_sand_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefill',
            name='date_prefil',
        ),
        migrations.RemoveField(
            model_name='prefill',
            name='loading_facility',
        ),
        migrations.RemoveField(
            model_name='prefill',
            name='po',
        ),
        migrations.RemoveField(
            model_name='prefill',
            name='total_sand',
        ),
        migrations.AddField(
            model_name='sandtype',
            name='date_prefil',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sandtype',
            name='loading_facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frac.LoadingFacility'),
        ),
        migrations.AddField(
            model_name='sandtype',
            name='po',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sandtype',
            name='total_sand',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
