# Generated by Django 3.0.6 on 2020-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0005_auto_20200524_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='sand_type',
        ),
        migrations.AddField(
            model_name='sandtype',
            name='well',
            field=models.ManyToManyField(blank=True, to='frac.Well'),
        ),
    ]
