# Generated by Django 3.0.6 on 2020-05-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0006_auto_20200524_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandtype',
            name='well',
        ),
        migrations.AddField(
            model_name='sandtype',
            name='well',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frac.Well'),
        ),
    ]
