# Generated by Django 3.0.6 on 2020-05-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0007_auto_20200524_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_num', models.CharField(max_length=30, null=True)),
                ('model', models.CharField(max_length=30, null=True)),
                ('year', models.CharField(max_length=30, null=True)),
                ('vin_num', models.CharField(max_length=30, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_num', models.CharField(max_length=30, null=True)),
                ('model', models.CharField(max_length=30, null=True)),
                ('year', models.CharField(max_length=30, null=True)),
                ('color', models.CharField(max_length=30, null=True)),
                ('vin_num', models.CharField(max_length=30, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Prefill',
        ),
    ]
