# Generated by Django 3.0.6 on 2020-05-31 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0009_driver'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('truck', 'trailer')},
        ),
    ]
