# Generated by Django 3.0.6 on 2020-06-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0010_auto_20200531_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
