# Generated by Django 3.0.6 on 2020-06-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0011_driver_busy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='busy',
            new_name='available',
        ),
    ]
