# Generated by Django 3.0.6 on 2020-06-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0014_auto_20200603_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Dispatched', 'Dispatched'), ('Loaded', 'Loaded'), ('Complete', 'Complete')], max_length=100, null=True),
        ),
    ]
