# Generated by Django 3.0.6 on 2020-06-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0015_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Dispatched', 'Dispatched'), ('Loaded', 'Loaded'), ('Complete', 'Complete')], default='Dispatched', max_length=100, null=True),
        ),
    ]
