# Generated by Django 3.0.6 on 2020-06-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0016_auto_20200603_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='well_name',
            new_name='well',
        ),
    ]
