# Generated by Django 3.0.6 on 2020-06-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0017_auto_20200603_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='load_weight',
            new_name='request_weight',
        ),
        migrations.AddField(
            model_name='order',
            name='actual_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='bol_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='load_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='load_time_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='load_time_out',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='loc_arrive_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='loc_arrive_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='loc_depart_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='loc_depart_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
