# Generated by Django 3.0.6 on 2020-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0018_auto_20200603_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
