# Generated by Django 3.0.6 on 2020-06-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0019_auto_20200605_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
