# Generated by Django 3.0.6 on 2020-06-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0021_auto_20200606_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='available',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
