# Generated by Django 3.0.6 on 2020-06-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0022_auto_20200606_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandtype',
            name='date_prefil',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
