# Generated by Django 3.0.6 on 2020-06-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0023_auto_20200610_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandtype',
            name='date_prefil',
            field=models.DateField(null=True),
        ),
    ]
