# Generated by Django 3.0.6 on 2020-06-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0024_auto_20200610_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandtype',
            name='date_prefil',
        ),
        migrations.AddField(
            model_name='sandtype',
            name='date_prefill',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
