# Generated by Django 3.0.6 on 2020-06-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0025_auto_20200610_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sandtype',
            old_name='name',
            new_name='sand_name',
        ),
    ]
