# Generated by Django 3.0.6 on 2020-06-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0028_auto_20200614_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='website',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='serviceco',
            name='website',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sandtype',
            name='date_prefill',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sandtype',
            name='po',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sandtype',
            name='total_sand',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
