# Generated by Django 3.0.6 on 2020-06-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0029_auto_20200626_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='website',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='serviceco',
            name='website',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
