# Generated by Django 3.0.6 on 2020-06-26 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0030_auto_20200626_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frac.Operator'),
        ),
    ]
