# Generated by Django 3.0.6 on 2020-06-26 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frac', '0031_auto_20200626_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frac.Trailer'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frac.Truck'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frac.Driver'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frac.SandType'),
        ),
        migrations.AlterField(
            model_name='order',
            name='well',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frac.Well'),
        ),
        migrations.AlterField(
            model_name='sandtype',
            name='loading_facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frac.LoadingFacility'),
        ),
        migrations.AlterField(
            model_name='sandtype',
            name='well',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frac.Well'),
        ),
        migrations.AlterField(
            model_name='well',
            name='crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frac.Crew'),
        ),
        migrations.AlterField(
            model_name='well',
            name='serviceco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frac.ServiceCo'),
        ),
    ]
